version: "3.7"
services:
  server:
    build:
      context: ./docker
      dockerfile: DockerfilePsvita      
    container_name: dreerally-dev-container
    stdin_open: true
    tty: true
    volumes:
      - .:/dreerally:cached 

  switch-builder: # New Nintendo Switch service
    build:
      context: ./docker
      dockerfile: DockerfileSwitch # Use the new Dockerfile
    container_name: dreerally-switch-builder # Unique container name
    stdin_open: true
    tty: true
    volumes:
      - .:/dreerally:cached # Mount the project directory
    # Optionally, define a default command or working directory if different from Dockerfile
    # working_dir: /dreerally
    # command: make -f Makefile.switch